# Generated by Django 5.0 on 2023-12-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='content',
            field=models.JSONField(),
        ),
    ]
