# Generated by Django 5.0 on 2023-12-14 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_phrase_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctPhrase', models.JSONField()),
                ('wrongPhrase', models.JSONField()),
                ('createDatetime', models.DateTimeField(auto_now_add=True)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.phrase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
