# Generated by Django 5.0 on 2024-03-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
