# Generated by Django 5.0 on 2024-03-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_paragraph_link_alter_recommend_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='link_ID',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='recommend',
            name='link_ID',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
